version: 2
updates:
  - package-ecosystem: pub
    directory: /gen/dart/version
    schedule:
      interval: weekly
    versioning-strategy: increase-if-necessary
    groups:
      dart:
        patterns:
          - "*"
  - package-ecosystem: gomod
    directory: /gen/golang/version
    schedule:
      interval: weekly
    groups:
      golang:
        patterns:
          - "*"
  - package-ecosystem: uv
    directory: /gen/python/version
    schedule:
      interval: weekly
    groups:
      python:
        patterns:
          - "*"
  - package-ecosystem: npm
    directory: /gen/typescript/version
    schedule:
      interval: weekly
    versioning-strategy: increase-if-necessary
    groups:
      typescript:
        patterns:
          - "*"
  - package-ecosystem: github-actions
    directory: "/"
    schedule:
      interval: weekly
  - package-ecosystem: npm
    target-branch: swagger-ui-pages
    directory: /swagger-ui
    schedule:
      interval: weekly
    versioning-strategy: increase-if-necessary
    groups:
      swagger-ui:
        patterns:
          - "swagger-ui-dist"
