repos:
- repo: local
  hooks:
  - id: make-lint-specs
    name: make lint-specs
    entry: make lint-specs
    language: system
    pass_filenames: false
    files: ^(spec/.*openapi\.yaml)$
  - id: make-lint-other
    name: make lint-other
    entry: make lint-other
    language: system
    pass_filenames: false
