extends: "spectral:oas"
rules:
  # spectral rules
  oas3-missing-example: off
  # vacuum rules
  component-description: off
  # custom rules
  component-description-except-schemas:
    description: >
      Require descriptions for components (excluding components.schemas).
      The last one is excluded, as it's too verbose.
    message: "Component is missing a description"
    severity: warn
    recommended: true
    formats: [ oas3, oas3_1 ]
    given:
      - $.components.parameters.*
      - $.components.requestBodies.*
      - $.components.responses.*
      - $.components.examples.*
      - $.components.headers.*
      - $.components.links.*
      - $.components.callbacks.*
      - $.components.securitySchemes.*
      - $.components.pathItems.* # OAS 3.1
    then:
      field: description
      function: truthy
  description-ends-with-dot:
    description: All descriptions must end with a period.
    message: "Schema description must end with a '.'"
    severity: warn
    recommended: true
    # Check description fields on objects, but avoid false positives for
    # schema property names like properties.description.
    given: "$..[?(@ && @.description)].description"
    then:
      function: schema
      functionOptions:
        schema:
          if:
            type: string
          then:
            pattern: "^[\\s\\S]*\\.\\s*$"
  object-additionalProperties-defined:
    description: Object schemas should explicitly declare additionalProperties.
    message: "Schema is an object but does not declare additionalProperties."
    severity: warn
    recommended: true
    resolved: false
    given:
      - "$..[?(@.type == 'object' && !@['$ref'])]"
      - "$..[?(@.properties && !@['$ref'])]"
    then:
      field: additionalProperties
      function: defined
