extends: default

rules:
  document-start: disable

  line-length:
    max: 80
    allow-non-breakable-words: true
    allow-non-breakable-inline-mappings: true

  brackets:
    max-spaces-inside: 1
    min-spaces-inside: 1

  indentation:
    spaces: 2
    indent-sequences: consistent
