// This file is auto-generated by @hey-api/openapi-ts

import type { Client, Options as Options2, TDataShape } from './client';
import { client } from './client.gen';
import type { CourseOverviewByIdData, CourseOverviewByIdErrors, CourseOverviewByIdResponses, CourseSummaryByIdData, CourseSummaryByIdErrors, CourseSummaryByIdResponses, CourseThemeSummaryByIdData, CourseThemeSummaryByIdErrors, CourseThemeSummaryByIdResponses, CurrentStudentData, CurrentStudentErrors, CurrentStudentResponses, GenerateContentDownloadLinkData, GenerateContentDownloadLinkErrors, GenerateContentDownloadLinkResponses, ListStudentCoursesData, ListStudentCoursesErrors, ListStudentCoursesResponses, LongreadMaterialsByIdData, LongreadMaterialsByIdErrors, LongreadMaterialsByIdResponses, LongreadSummaryByIdData, LongreadSummaryByIdErrors, LongreadSummaryByIdResponses, TaskByIdData, TaskByIdErrors, TaskByIdResponses } from './types.gen';
import { zCourseOverviewByIdResponse2, zCourseSummaryByIdResponse2, zCourseThemeSummaryByIdResponse2, zCurrentStudentResponse2, zGenerateContentDownloadLinkResponse2, zListStudentCoursesResponse2, zLongreadMaterialsByIdResponse2, zLongreadSummaryByIdResponse2, zTaskByIdResponse2 } from './zod.gen';

export type Options<TData extends TDataShape = TDataShape, ThrowOnError extends boolean = boolean, TResponse = unknown> = Options2<TData, ThrowOnError, TResponse> & {
    /**
     * You can provide a client instance returned by `createClient()` instead of
     * individual options. This might be also useful if you want to implement a
     * custom client.
     */
    client?: Client;
    /**
     * You can pass arbitrary values through the `meta` object. This can be
     * used to access values that aren't defined as part of the SDK function.
     */
    meta?: Record<string, unknown>;
};

/**
 * Get current student.
 *
 * Returns authenticated student data.
 */
export const currentStudent = <ThrowOnError extends boolean = false>(options?: Options<CurrentStudentData, ThrowOnError>) => (options?.client ?? client).get<CurrentStudentResponses, CurrentStudentErrors, ThrowOnError>({
    responseValidator: async (data) => await zCurrentStudentResponse2.parseAsync(data),
    security: [{
            in: 'cookie',
            name: 'bff.cookie',
            type: 'apiKey'
        }],
    url: '/micro-lms/students/me',
    ...options
});

/**
 * List courses for the current student.
 *
 * Returns courses summary the authenticated student is enrolled in.
 *
 */
export const listStudentCourses = <ThrowOnError extends boolean = false>(options?: Options<ListStudentCoursesData, ThrowOnError>) => (options?.client ?? client).get<ListStudentCoursesResponses, ListStudentCoursesErrors, ThrowOnError>({
    responseValidator: async (data) => await zListStudentCoursesResponse2.parseAsync(data),
    security: [{
            in: 'cookie',
            name: 'bff.cookie',
            type: 'apiKey'
        }],
    url: '/micro-lms/courses/student',
    ...options
});

/**
 * Get course summary by its ID.
 *
 * Returns summary information about a course by courseId.
 */
export const courseSummaryById = <ThrowOnError extends boolean = false>(options: Options<CourseSummaryByIdData, ThrowOnError>) => (options.client ?? client).get<CourseSummaryByIdResponses, CourseSummaryByIdErrors, ThrowOnError>({
    responseValidator: async (data) => await zCourseSummaryByIdResponse2.parseAsync(data),
    security: [{
            in: 'cookie',
            name: 'bff.cookie',
            type: 'apiKey'
        }],
    url: '/micro-lms/courses/{courseId}',
    ...options
});

/**
 * Get course overview by its ID.
 *
 * Returns course overview by courseId. Overview consists of unit items called as themes, which are typically weekly modules of longread IDs and exercise items.
 *
 */
export const courseOverviewById = <ThrowOnError extends boolean = false>(options: Options<CourseOverviewByIdData, ThrowOnError>) => (options.client ?? client).get<CourseOverviewByIdResponses, CourseOverviewByIdErrors, ThrowOnError>({
    responseValidator: async (data) => await zCourseOverviewByIdResponse2.parseAsync(data),
    security: [{
            in: 'cookie',
            name: 'bff.cookie',
            type: 'apiKey'
        }],
    url: '/micro-lms/courses/{courseId}/overview',
    ...options
});

/**
 * Get course theme summary by its ID.
 *
 * Returns summary information about a course theme by themeId.
 */
export const courseThemeSummaryById = <ThrowOnError extends boolean = false>(options: Options<CourseThemeSummaryByIdData, ThrowOnError>) => (options.client ?? client).get<CourseThemeSummaryByIdResponses, CourseThemeSummaryByIdErrors, ThrowOnError>({
    responseValidator: async (data) => await zCourseThemeSummaryByIdResponse2.parseAsync(data),
    security: [{
            in: 'cookie',
            name: 'bff.cookie',
            type: 'apiKey'
        }],
    url: '/micro-lms/themes/{themeId}',
    ...options
});

/**
 * Get longread summary by its ID.
 *
 * Returns summary information about a longread item by longreadId.
 *
 */
export const longreadSummaryById = <ThrowOnError extends boolean = false>(options: Options<LongreadSummaryByIdData, ThrowOnError>) => (options.client ?? client).get<LongreadSummaryByIdResponses, LongreadSummaryByIdErrors, ThrowOnError>({
    responseValidator: async (data) => await zLongreadSummaryByIdResponse2.parseAsync(data),
    security: [{
            in: 'cookie',
            name: 'bff.cookie',
            type: 'apiKey'
        }],
    url: '/micro-lms/longreads/{longreadId}',
    ...options
});

/**
 * Get longread materials by its ID.
 *
 * Returns longread materials by longreadId. Materials are blocks like markdown, files and exercises. Blocks are declared for each longread.
 *
 */
export const longreadMaterialsById = <ThrowOnError extends boolean = false>(options: Options<LongreadMaterialsByIdData, ThrowOnError>) => (options.client ?? client).get<LongreadMaterialsByIdResponses, LongreadMaterialsByIdErrors, ThrowOnError>({
    responseValidator: async (data) => await zLongreadMaterialsByIdResponse2.parseAsync(data),
    security: [{
            in: 'cookie',
            name: 'bff.cookie',
            type: 'apiKey'
        }],
    url: '/micro-lms/longreads/{longreadId}/materials',
    ...options
});

/**
 * Get task by its ID.
 *
 * Returns task by taskId.
 */
export const taskById = <ThrowOnError extends boolean = false>(options: Options<TaskByIdData, ThrowOnError>) => (options.client ?? client).get<TaskByIdResponses, TaskByIdErrors, ThrowOnError>({
    responseValidator: async (data) => await zTaskByIdResponse2.parseAsync(data),
    security: [{
            in: 'cookie',
            name: 'bff.cookie',
            type: 'apiKey'
        }],
    url: '/micro-lms/tasks/{taskId}',
    ...options
});

/**
 * Generate content download link.
 *
 * Returns generated content download link by filename.
 */
export const generateContentDownloadLink = <ThrowOnError extends boolean = false>(options: Options<GenerateContentDownloadLinkData, ThrowOnError>) => (options.client ?? client).get<GenerateContentDownloadLinkResponses, GenerateContentDownloadLinkErrors, ThrowOnError>({
    responseValidator: async (data) => await zGenerateContentDownloadLinkResponse2.parseAsync(data),
    security: [{
            in: 'cookie',
            name: 'bff.cookie',
            type: 'apiKey'
        }],
    url: '/micro-lms/content/download-link',
    ...options
});
