name: open_cu_services_gen_dart_version
version: 0.0.0
publish_to: none

environment:
  sdk: "^3.8.0"

dependencies:
  chopper: ^8.5.0
  collection: "^1.19.1"
  http: "^1.6.0"
  json_annotation: "^4.11.0"

dev_dependencies:
  swagger_dart_code_generator: "4.1.1"
  build_runner: 2.13.1
  chopper_generator: 8.6.1
  json_serializable: 6.13.1
