# This file is @generated by gen-sdk-python.

"""Open CU Services LMS API Python SDK (based on spec/lmsapi/v0.1.0)"""

from .client import AuthenticatedClient, Client
from .defaults import (
    BFF_COOKIE_NAME,
    DEFAULT_BASE_URL,
    DEFAULT_USER_AGENT,
    SDK_VERSION,
    SPEC_VERSION,
    BffCookieAuthenticatedClient,
    BffCookieIsEmptyError,
    create_lms_client,
    create_lms_client_from_env,
)

__version__ = "0.1.0"

__all__ = (
    "AuthenticatedClient",
    "BFF_COOKIE_NAME",
    "BffCookieAuthenticatedClient",
    "BffCookieIsEmptyError",
    "Client",
    "DEFAULT_BASE_URL",
    "DEFAULT_USER_AGENT",
    "SDK_VERSION",
    "SPEC_VERSION",
    "__version__",
    "create_lms_client",
    "create_lms_client_from_env",
)
