// Code generated by gen-sdk-golang, DO NOT EDIT.

/* Package lmsapi provides SDK for the CU LMS API. (based on spec/lmsapi/v0.1.0). */
package lmsapi

const (
	DefaultBaseURL   = "https://my.centraluniversity.ru/api"
	DefaultUserAgent = "Open-CU-Services/Go"
	sdkVersion       = "0.1.0"
	specVersion      = "0.1.0"
)

func SDKVersion() string {
	return sdkVersion
}

func SpecVersion() string {
	return specVersion
}
