// Code generated by ogen, DO NOT EDIT.

package lmsapi

import (
	"context"
	"net/http"
	"net/url"
	"strings"
	"time"

	"github.com/go-faster/errors"
	"github.com/ogen-go/ogen/conv"
	ht "github.com/ogen-go/ogen/http"
	"github.com/ogen-go/ogen/ogenerrors"
	"github.com/ogen-go/ogen/otelogen"
	"github.com/ogen-go/ogen/uri"
	"go.opentelemetry.io/otel/attribute"
	"go.opentelemetry.io/otel/codes"
	"go.opentelemetry.io/otel/metric"
	semconv "go.opentelemetry.io/otel/semconv/v1.39.0"
	"go.opentelemetry.io/otel/trace"
)

type requestConfig struct {
	Client        ht.Client
	ServerURL     *url.URL
	EditRequest   func(req *http.Request) error
	EditResponse  func(resp *http.Response) error
	DebugResponse *DebugResponse
}

func (cfg *requestConfig) setDefaults(c baseClient) {
	if cfg.Client == nil {
		cfg.Client = c.cfg.Client
	}
}

func (cfg *requestConfig) onRequest(req *http.Request) error {
	if fn := cfg.EditRequest; fn != nil {
		return fn(req)
	}
	return nil
}

func (cfg *requestConfig) onResponse(resp *http.Response) error {
	if fn := cfg.EditResponse; fn != nil {
		return fn(resp)
	}
	return nil
}

// RequestOption defines options for request.
type RequestOption func(cfg *requestConfig)

// WithRequestClient sets client for request.
func WithRequestClient(client ht.Client) RequestOption {
	return func(cfg *requestConfig) {
		cfg.Client = client
	}
}

// WithServerURL sets client for request.
func WithServerURL(u *url.URL) RequestOption {
	return func(cfg *requestConfig) {
		cfg.ServerURL = u
	}
}

// WithEditRequest sets function to edit request.
func WithEditRequest(fn func(req *http.Request) error) RequestOption {
	return func(cfg *requestConfig) {
		cfg.EditRequest = fn
	}
}

// WithEditResponse sets function to edit response.
func WithEditResponse(fn func(resp *http.Response) error) RequestOption {
	return func(cfg *requestConfig) {
		cfg.EditResponse = fn
	}
}

func trimTrailingSlashes(u *url.URL) {
	u.Path = strings.TrimRight(u.Path, "/")
	u.RawPath = strings.TrimRight(u.RawPath, "/")
}

// Invoker invokes operations described by OpenAPI v3 specification.
type Invoker interface {
	// CourseOverviewById invokes courseOverviewById operation.
	//
	// Returns course overview by courseId. Overview consists of unit items called as themes, which are
	// typically weekly modules of longread IDs and exercise items.
	//
	// GET /micro-lms/courses/{courseId}/overview
	CourseOverviewById(ctx context.Context, params CourseOverviewByIdParams, options ...RequestOption) (CourseOverviewByIdRes, error)
	// CourseSummaryById invokes courseSummaryById operation.
	//
	// Returns summary information about a course by courseId.
	//
	// GET /micro-lms/courses/{courseId}
	CourseSummaryById(ctx context.Context, params CourseSummaryByIdParams, options ...RequestOption) (CourseSummaryByIdRes, error)
	// CourseThemeSummaryById invokes courseThemeSummaryById operation.
	//
	// Returns summary information about a course theme by themeId.
	//
	// GET /micro-lms/themes/{themeId}
	CourseThemeSummaryById(ctx context.Context, params CourseThemeSummaryByIdParams, options ...RequestOption) (CourseThemeSummaryByIdRes, error)
	// CurrentStudent invokes currentStudent operation.
	//
	// Returns authenticated student data.
	//
	// GET /micro-lms/students/me
	CurrentStudent(ctx context.Context, options ...RequestOption) (CurrentStudentRes, error)
	// GenerateContentDownloadLink invokes generateContentDownloadLink operation.
	//
	// Returns generated content download link by filename.
	//
	// GET /micro-lms/content/download-link
	GenerateContentDownloadLink(ctx context.Context, params GenerateContentDownloadLinkParams, options ...RequestOption) (GenerateContentDownloadLinkRes, error)
	// ListStudentCourses invokes listStudentCourses operation.
	//
	// Returns courses summary the authenticated student is enrolled in.
	//
	// GET /micro-lms/courses/student
	ListStudentCourses(ctx context.Context, params ListStudentCoursesParams, options ...RequestOption) (ListStudentCoursesRes, error)
	// LongreadMaterialsById invokes longreadMaterialsById operation.
	//
	// Returns longread materials by longreadId. Materials are blocks like markdown, files and exercises.
	// Blocks are declared for each longread.
	//
	// GET /micro-lms/longreads/{longreadId}/materials
	LongreadMaterialsById(ctx context.Context, params LongreadMaterialsByIdParams, options ...RequestOption) (LongreadMaterialsByIdRes, error)
	// LongreadSummaryById invokes longreadSummaryById operation.
	//
	// Returns summary information about a longread item by longreadId.
	//
	// GET /micro-lms/longreads/{longreadId}
	LongreadSummaryById(ctx context.Context, params LongreadSummaryByIdParams, options ...RequestOption) (LongreadSummaryByIdRes, error)
	// TaskById invokes taskById operation.
	//
	// Returns task by taskId.
	//
	// GET /micro-lms/tasks/{taskId}
	TaskById(ctx context.Context, params TaskByIdParams, options ...RequestOption) (TaskByIdRes, error)
}

// Client implements OAS client.
type Client struct {
	serverURL *url.URL
	sec       SecuritySource
	baseClient
}

// NewClient initializes new Client defined by OAS.
func NewClient(serverURL string, sec SecuritySource, opts ...ClientOption) (*Client, error) {
	u, err := url.Parse(serverURL)
	if err != nil {
		return nil, err
	}
	trimTrailingSlashes(u)

	c, err := newClientConfig(opts...).baseClient()
	if err != nil {
		return nil, err
	}
	return &Client{
		serverURL:  u,
		sec:        sec,
		baseClient: c,
	}, nil
}
func (c *Client) onRequest(ctx context.Context, req *http.Request) error {
	for _, fn := range c.cfg.RequestEditors {
		if err := fn(ctx, req); err != nil {
			return err
		}
	}
	return nil
}

func (c *Client) onResponse(ctx context.Context, resp *http.Response) error {
	for _, fn := range c.cfg.ResponseEditors {
		if err := fn(ctx, resp); err != nil {
			return err
		}
	}
	return nil
}

// CourseOverviewById invokes courseOverviewById operation.
//
// Returns course overview by courseId. Overview consists of unit items called as themes, which are
// typically weekly modules of longread IDs and exercise items.
//
// GET /micro-lms/courses/{courseId}/overview
func (c *Client) CourseOverviewById(ctx context.Context, params CourseOverviewByIdParams, options ...RequestOption) (CourseOverviewByIdRes, error) {
	return callClientDebugResponse(c, func(debugResponse *DebugResponse) (CourseOverviewByIdRes, error) {
		return c.sendCourseOverviewById(ctx, params, appendDebugResponseRequestOption(options, debugResponse)...)
	})

}

func (c *Client) sendCourseOverviewById(ctx context.Context, params CourseOverviewByIdParams, requestOptions ...RequestOption) (res CourseOverviewByIdRes, err error) {
	otelAttrs := []attribute.KeyValue{
		otelogen.OperationID("courseOverviewById"),
		semconv.HTTPRequestMethodKey.String("GET"),
		semconv.URLTemplateKey.String("/micro-lms/courses/{courseId}/overview"),
	}
	otelAttrs = append(otelAttrs, c.cfg.Attributes...)

	// Run stopwatch.
	startTime := time.Now()
	defer func() {
		// Use floating point division here for higher precision (instead of Millisecond method).
		elapsedDuration := time.Since(startTime)
		c.duration.Record(ctx, float64(elapsedDuration)/float64(time.Millisecond), metric.WithAttributes(otelAttrs...))
	}()

	// Increment request counter.
	c.requests.Add(ctx, 1, metric.WithAttributes(otelAttrs...))

	// Start a span for this request.
	ctx, span := c.cfg.Tracer.Start(ctx, CourseOverviewByIdOperation,
		trace.WithAttributes(otelAttrs...),
		clientSpanKind,
	)
	// Track stage for error reporting.
	var stage string
	defer func() {
		if err != nil {
			span.RecordError(err)
			span.SetStatus(codes.Error, stage)
			c.errors.Add(ctx, 1, metric.WithAttributes(otelAttrs...))
		}
		span.End()
	}()

	var reqCfg requestConfig
	reqCfg.setDefaults(c.baseClient)
	for _, o := range requestOptions {
		o(&reqCfg)
	}

	stage = "BuildURL"
	u := c.serverURL
	if override := reqCfg.ServerURL; override != nil {
		u = override
	}
	u = uri.Clone(u)
	var pathParts [3]string
	pathParts[0] = "/micro-lms/courses/"
	{
		// Encode "courseId" parameter.
		e := uri.NewPathEncoder(uri.PathEncoderConfig{
			Param:   "courseId",
			Style:   uri.PathStyleSimple,
			Explode: false,
		})
		if err := func() error {
			if unwrapped := int(params.CourseId); true {
				return e.EncodeValue(conv.IntToString(unwrapped))
			}
			return nil
		}(); err != nil {
			return res, errors.Wrap(err, "encode path")
		}
		encoded, err := e.Result()
		if err != nil {
			return res, errors.Wrap(err, "encode path")
		}
		pathParts[1] = encoded
	}
	pathParts[2] = "/overview"
	uri.AddPathParts(u, pathParts[:]...)

	stage = "EncodeRequest"
	r, err := ht.NewRequest(ctx, "GET", u)
	if err != nil {
		return res, errors.Wrap(err, "create request")
	}

	{
		type bitset = [1]uint8
		var satisfied bitset
		{
			stage = "Security:BffCookie"
			switch err := c.securityBffCookie(ctx, CourseOverviewByIdOperation, r); {
			case err == nil: // if NO error
				satisfied[0] |= 1 << 0
			case errors.Is(err, ogenerrors.ErrSkipClientSecurity):
				// Skip this security.
			default:
				return res, errors.Wrap(err, "security \"BffCookie\"")
			}
		}

		if ok := func() bool {
		nextRequirement:
			for _, requirement := range []bitset{
				{0b00000001},
			} {
				for i, mask := range requirement {
					if satisfied[i]&mask != mask {
						continue nextRequirement
					}
				}
				return true
			}
			return false
		}(); !ok {
			return res, ogenerrors.ErrSecurityRequirementIsNotSatisfied
		}
	}

	if err := c.onRequest(ctx, r); err != nil {
		return res, errors.Wrap(err, "client edit request")
	}

	if err := reqCfg.onRequest(r); err != nil {
		return res, errors.Wrap(err, "edit request")
	}

	stage = "SendRequest"
	resp, err := reqCfg.Client.Do(r)
	if err != nil {
		return res, errors.Wrap(err, "do request")
	}
	body := resp.Body
	defer body.Close()

	if err := c.onResponse(ctx, resp); err != nil {
		return res, errors.Wrap(err, "client edit response")
	}

	if err := reqCfg.onResponse(resp); err != nil {
		return res, errors.Wrap(err, "edit response")
	}

	stage = "DecodeResponse"
	result, err := decodeCourseOverviewByIdResponse(resp, reqCfg.DebugResponse)
	if err != nil {
		return res, errors.Wrap(err, "decode response")
	}

	return result, nil
}

// CourseSummaryById invokes courseSummaryById operation.
//
// Returns summary information about a course by courseId.
//
// GET /micro-lms/courses/{courseId}
func (c *Client) CourseSummaryById(ctx context.Context, params CourseSummaryByIdParams, options ...RequestOption) (CourseSummaryByIdRes, error) {
	return callClientDebugResponse(c, func(debugResponse *DebugResponse) (CourseSummaryByIdRes, error) {
		return c.sendCourseSummaryById(ctx, params, appendDebugResponseRequestOption(options, debugResponse)...)
	})

}

func (c *Client) sendCourseSummaryById(ctx context.Context, params CourseSummaryByIdParams, requestOptions ...RequestOption) (res CourseSummaryByIdRes, err error) {
	otelAttrs := []attribute.KeyValue{
		otelogen.OperationID("courseSummaryById"),
		semconv.HTTPRequestMethodKey.String("GET"),
		semconv.URLTemplateKey.String("/micro-lms/courses/{courseId}"),
	}
	otelAttrs = append(otelAttrs, c.cfg.Attributes...)

	// Run stopwatch.
	startTime := time.Now()
	defer func() {
		// Use floating point division here for higher precision (instead of Millisecond method).
		elapsedDuration := time.Since(startTime)
		c.duration.Record(ctx, float64(elapsedDuration)/float64(time.Millisecond), metric.WithAttributes(otelAttrs...))
	}()

	// Increment request counter.
	c.requests.Add(ctx, 1, metric.WithAttributes(otelAttrs...))

	// Start a span for this request.
	ctx, span := c.cfg.Tracer.Start(ctx, CourseSummaryByIdOperation,
		trace.WithAttributes(otelAttrs...),
		clientSpanKind,
	)
	// Track stage for error reporting.
	var stage string
	defer func() {
		if err != nil {
			span.RecordError(err)
			span.SetStatus(codes.Error, stage)
			c.errors.Add(ctx, 1, metric.WithAttributes(otelAttrs...))
		}
		span.End()
	}()

	var reqCfg requestConfig
	reqCfg.setDefaults(c.baseClient)
	for _, o := range requestOptions {
		o(&reqCfg)
	}

	stage = "BuildURL"
	u := c.serverURL
	if override := reqCfg.ServerURL; override != nil {
		u = override
	}
	u = uri.Clone(u)
	var pathParts [2]string
	pathParts[0] = "/micro-lms/courses/"
	{
		// Encode "courseId" parameter.
		e := uri.NewPathEncoder(uri.PathEncoderConfig{
			Param:   "courseId",
			Style:   uri.PathStyleSimple,
			Explode: false,
		})
		if err := func() error {
			if unwrapped := int(params.CourseId); true {
				return e.EncodeValue(conv.IntToString(unwrapped))
			}
			return nil
		}(); err != nil {
			return res, errors.Wrap(err, "encode path")
		}
		encoded, err := e.Result()
		if err != nil {
			return res, errors.Wrap(err, "encode path")
		}
		pathParts[1] = encoded
	}
	uri.AddPathParts(u, pathParts[:]...)

	stage = "EncodeRequest"
	r, err := ht.NewRequest(ctx, "GET", u)
	if err != nil {
		return res, errors.Wrap(err, "create request")
	}

	{
		type bitset = [1]uint8
		var satisfied bitset
		{
			stage = "Security:BffCookie"
			switch err := c.securityBffCookie(ctx, CourseSummaryByIdOperation, r); {
			case err == nil: // if NO error
				satisfied[0] |= 1 << 0
			case errors.Is(err, ogenerrors.ErrSkipClientSecurity):
				// Skip this security.
			default:
				return res, errors.Wrap(err, "security \"BffCookie\"")
			}
		}

		if ok := func() bool {
		nextRequirement:
			for _, requirement := range []bitset{
				{0b00000001},
			} {
				for i, mask := range requirement {
					if satisfied[i]&mask != mask {
						continue nextRequirement
					}
				}
				return true
			}
			return false
		}(); !ok {
			return res, ogenerrors.ErrSecurityRequirementIsNotSatisfied
		}
	}

	if err := c.onRequest(ctx, r); err != nil {
		return res, errors.Wrap(err, "client edit request")
	}

	if err := reqCfg.onRequest(r); err != nil {
		return res, errors.Wrap(err, "edit request")
	}

	stage = "SendRequest"
	resp, err := reqCfg.Client.Do(r)
	if err != nil {
		return res, errors.Wrap(err, "do request")
	}
	body := resp.Body
	defer body.Close()

	if err := c.onResponse(ctx, resp); err != nil {
		return res, errors.Wrap(err, "client edit response")
	}

	if err := reqCfg.onResponse(resp); err != nil {
		return res, errors.Wrap(err, "edit response")
	}

	stage = "DecodeResponse"
	result, err := decodeCourseSummaryByIdResponse(resp, reqCfg.DebugResponse)
	if err != nil {
		return res, errors.Wrap(err, "decode response")
	}

	return result, nil
}

// CourseThemeSummaryById invokes courseThemeSummaryById operation.
//
// Returns summary information about a course theme by themeId.
//
// GET /micro-lms/themes/{themeId}
func (c *Client) CourseThemeSummaryById(ctx context.Context, params CourseThemeSummaryByIdParams, options ...RequestOption) (CourseThemeSummaryByIdRes, error) {
	return callClientDebugResponse(c, func(debugResponse *DebugResponse) (CourseThemeSummaryByIdRes, error) {
		return c.sendCourseThemeSummaryById(ctx, params, appendDebugResponseRequestOption(options, debugResponse)...)
	})

}

func (c *Client) sendCourseThemeSummaryById(ctx context.Context, params CourseThemeSummaryByIdParams, requestOptions ...RequestOption) (res CourseThemeSummaryByIdRes, err error) {
	otelAttrs := []attribute.KeyValue{
		otelogen.OperationID("courseThemeSummaryById"),
		semconv.HTTPRequestMethodKey.String("GET"),
		semconv.URLTemplateKey.String("/micro-lms/themes/{themeId}"),
	}
	otelAttrs = append(otelAttrs, c.cfg.Attributes...)

	// Run stopwatch.
	startTime := time.Now()
	defer func() {
		// Use floating point division here for higher precision (instead of Millisecond method).
		elapsedDuration := time.Since(startTime)
		c.duration.Record(ctx, float64(elapsedDuration)/float64(time.Millisecond), metric.WithAttributes(otelAttrs...))
	}()

	// Increment request counter.
	c.requests.Add(ctx, 1, metric.WithAttributes(otelAttrs...))

	// Start a span for this request.
	ctx, span := c.cfg.Tracer.Start(ctx, CourseThemeSummaryByIdOperation,
		trace.WithAttributes(otelAttrs...),
		clientSpanKind,
	)
	// Track stage for error reporting.
	var stage string
	defer func() {
		if err != nil {
			span.RecordError(err)
			span.SetStatus(codes.Error, stage)
			c.errors.Add(ctx, 1, metric.WithAttributes(otelAttrs...))
		}
		span.End()
	}()

	var reqCfg requestConfig
	reqCfg.setDefaults(c.baseClient)
	for _, o := range requestOptions {
		o(&reqCfg)
	}

	stage = "BuildURL"
	u := c.serverURL
	if override := reqCfg.ServerURL; override != nil {
		u = override
	}
	u = uri.Clone(u)
	var pathParts [2]string
	pathParts[0] = "/micro-lms/themes/"
	{
		// Encode "themeId" parameter.
		e := uri.NewPathEncoder(uri.PathEncoderConfig{
			Param:   "themeId",
			Style:   uri.PathStyleSimple,
			Explode: false,
		})
		if err := func() error {
			if unwrapped := int(params.ThemeId); true {
				return e.EncodeValue(conv.IntToString(unwrapped))
			}
			return nil
		}(); err != nil {
			return res, errors.Wrap(err, "encode path")
		}
		encoded, err := e.Result()
		if err != nil {
			return res, errors.Wrap(err, "encode path")
		}
		pathParts[1] = encoded
	}
	uri.AddPathParts(u, pathParts[:]...)

	stage = "EncodeRequest"
	r, err := ht.NewRequest(ctx, "GET", u)
	if err != nil {
		return res, errors.Wrap(err, "create request")
	}

	{
		type bitset = [1]uint8
		var satisfied bitset
		{
			stage = "Security:BffCookie"
			switch err := c.securityBffCookie(ctx, CourseThemeSummaryByIdOperation, r); {
			case err == nil: // if NO error
				satisfied[0] |= 1 << 0
			case errors.Is(err, ogenerrors.ErrSkipClientSecurity):
				// Skip this security.
			default:
				return res, errors.Wrap(err, "security \"BffCookie\"")
			}
		}

		if ok := func() bool {
		nextRequirement:
			for _, requirement := range []bitset{
				{0b00000001},
			} {
				for i, mask := range requirement {
					if satisfied[i]&mask != mask {
						continue nextRequirement
					}
				}
				return true
			}
			return false
		}(); !ok {
			return res, ogenerrors.ErrSecurityRequirementIsNotSatisfied
		}
	}

	if err := c.onRequest(ctx, r); err != nil {
		return res, errors.Wrap(err, "client edit request")
	}

	if err := reqCfg.onRequest(r); err != nil {
		return res, errors.Wrap(err, "edit request")
	}

	stage = "SendRequest"
	resp, err := reqCfg.Client.Do(r)
	if err != nil {
		return res, errors.Wrap(err, "do request")
	}
	body := resp.Body
	defer body.Close()

	if err := c.onResponse(ctx, resp); err != nil {
		return res, errors.Wrap(err, "client edit response")
	}

	if err := reqCfg.onResponse(resp); err != nil {
		return res, errors.Wrap(err, "edit response")
	}

	stage = "DecodeResponse"
	result, err := decodeCourseThemeSummaryByIdResponse(resp, reqCfg.DebugResponse)
	if err != nil {
		return res, errors.Wrap(err, "decode response")
	}

	return result, nil
}

// CurrentStudent invokes currentStudent operation.
//
// Returns authenticated student data.
//
// GET /micro-lms/students/me
func (c *Client) CurrentStudent(ctx context.Context, options ...RequestOption) (CurrentStudentRes, error) {
	return callClientDebugResponse(c, func(debugResponse *DebugResponse) (CurrentStudentRes, error) {
		return c.sendCurrentStudent(ctx, appendDebugResponseRequestOption(options, debugResponse)...)
	})

}

func (c *Client) sendCurrentStudent(ctx context.Context, requestOptions ...RequestOption) (res CurrentStudentRes, err error) {
	otelAttrs := []attribute.KeyValue{
		otelogen.OperationID("currentStudent"),
		semconv.HTTPRequestMethodKey.String("GET"),
		semconv.URLTemplateKey.String("/micro-lms/students/me"),
	}
	otelAttrs = append(otelAttrs, c.cfg.Attributes...)

	// Run stopwatch.
	startTime := time.Now()
	defer func() {
		// Use floating point division here for higher precision (instead of Millisecond method).
		elapsedDuration := time.Since(startTime)
		c.duration.Record(ctx, float64(elapsedDuration)/float64(time.Millisecond), metric.WithAttributes(otelAttrs...))
	}()

	// Increment request counter.
	c.requests.Add(ctx, 1, metric.WithAttributes(otelAttrs...))

	// Start a span for this request.
	ctx, span := c.cfg.Tracer.Start(ctx, CurrentStudentOperation,
		trace.WithAttributes(otelAttrs...),
		clientSpanKind,
	)
	// Track stage for error reporting.
	var stage string
	defer func() {
		if err != nil {
			span.RecordError(err)
			span.SetStatus(codes.Error, stage)
			c.errors.Add(ctx, 1, metric.WithAttributes(otelAttrs...))
		}
		span.End()
	}()

	var reqCfg requestConfig
	reqCfg.setDefaults(c.baseClient)
	for _, o := range requestOptions {
		o(&reqCfg)
	}

	stage = "BuildURL"
	u := c.serverURL
	if override := reqCfg.ServerURL; override != nil {
		u = override
	}
	u = uri.Clone(u)
	var pathParts [1]string
	pathParts[0] = "/micro-lms/students/me"
	uri.AddPathParts(u, pathParts[:]...)

	stage = "EncodeRequest"
	r, err := ht.NewRequest(ctx, "GET", u)
	if err != nil {
		return res, errors.Wrap(err, "create request")
	}

	{
		type bitset = [1]uint8
		var satisfied bitset
		{
			stage = "Security:BffCookie"
			switch err := c.securityBffCookie(ctx, CurrentStudentOperation, r); {
			case err == nil: // if NO error
				satisfied[0] |= 1 << 0
			case errors.Is(err, ogenerrors.ErrSkipClientSecurity):
				// Skip this security.
			default:
				return res, errors.Wrap(err, "security \"BffCookie\"")
			}
		}

		if ok := func() bool {
		nextRequirement:
			for _, requirement := range []bitset{
				{0b00000001},
			} {
				for i, mask := range requirement {
					if satisfied[i]&mask != mask {
						continue nextRequirement
					}
				}
				return true
			}
			return false
		}(); !ok {
			return res, ogenerrors.ErrSecurityRequirementIsNotSatisfied
		}
	}

	if err := c.onRequest(ctx, r); err != nil {
		return res, errors.Wrap(err, "client edit request")
	}

	if err := reqCfg.onRequest(r); err != nil {
		return res, errors.Wrap(err, "edit request")
	}

	stage = "SendRequest"
	resp, err := reqCfg.Client.Do(r)
	if err != nil {
		return res, errors.Wrap(err, "do request")
	}
	body := resp.Body
	defer body.Close()

	if err := c.onResponse(ctx, resp); err != nil {
		return res, errors.Wrap(err, "client edit response")
	}

	if err := reqCfg.onResponse(resp); err != nil {
		return res, errors.Wrap(err, "edit response")
	}

	stage = "DecodeResponse"
	result, err := decodeCurrentStudentResponse(resp, reqCfg.DebugResponse)
	if err != nil {
		return res, errors.Wrap(err, "decode response")
	}

	return result, nil
}

// GenerateContentDownloadLink invokes generateContentDownloadLink operation.
//
// Returns generated content download link by filename.
//
// GET /micro-lms/content/download-link
func (c *Client) GenerateContentDownloadLink(ctx context.Context, params GenerateContentDownloadLinkParams, options ...RequestOption) (GenerateContentDownloadLinkRes, error) {
	return callClientDebugResponse(c, func(debugResponse *DebugResponse) (GenerateContentDownloadLinkRes, error) {
		return c.sendGenerateContentDownloadLink(ctx, params, appendDebugResponseRequestOption(options, debugResponse)...)
	})

}

func (c *Client) sendGenerateContentDownloadLink(ctx context.Context, params GenerateContentDownloadLinkParams, requestOptions ...RequestOption) (res GenerateContentDownloadLinkRes, err error) {
	otelAttrs := []attribute.KeyValue{
		otelogen.OperationID("generateContentDownloadLink"),
		semconv.HTTPRequestMethodKey.String("GET"),
		semconv.URLTemplateKey.String("/micro-lms/content/download-link"),
	}
	otelAttrs = append(otelAttrs, c.cfg.Attributes...)

	// Run stopwatch.
	startTime := time.Now()
	defer func() {
		// Use floating point division here for higher precision (instead of Millisecond method).
		elapsedDuration := time.Since(startTime)
		c.duration.Record(ctx, float64(elapsedDuration)/float64(time.Millisecond), metric.WithAttributes(otelAttrs...))
	}()

	// Increment request counter.
	c.requests.Add(ctx, 1, metric.WithAttributes(otelAttrs...))

	// Start a span for this request.
	ctx, span := c.cfg.Tracer.Start(ctx, GenerateContentDownloadLinkOperation,
		trace.WithAttributes(otelAttrs...),
		clientSpanKind,
	)
	// Track stage for error reporting.
	var stage string
	defer func() {
		if err != nil {
			span.RecordError(err)
			span.SetStatus(codes.Error, stage)
			c.errors.Add(ctx, 1, metric.WithAttributes(otelAttrs...))
		}
		span.End()
	}()

	var reqCfg requestConfig
	reqCfg.setDefaults(c.baseClient)
	for _, o := range requestOptions {
		o(&reqCfg)
	}

	stage = "BuildURL"
	u := c.serverURL
	if override := reqCfg.ServerURL; override != nil {
		u = override
	}
	u = uri.Clone(u)
	var pathParts [1]string
	pathParts[0] = "/micro-lms/content/download-link"
	uri.AddPathParts(u, pathParts[:]...)

	stage = "EncodeQueryParams"
	q := uri.NewQueryEncoder()
	{
		// Encode "filename" parameter.
		cfg := uri.QueryParameterEncodingConfig{
			Name:    "filename",
			Style:   uri.QueryStyleForm,
			Explode: true,
		}

		if err := q.EncodeParam(cfg, func(e uri.Encoder) error {
			if unwrapped := string(params.Filename); true {
				return e.EncodeValue(conv.StringToString(unwrapped))
			}
			return nil
		}); err != nil {
			return res, errors.Wrap(err, "encode query")
		}
	}
	{
		// Encode "version" parameter.
		cfg := uri.QueryParameterEncodingConfig{
			Name:    "version",
			Style:   uri.QueryStyleForm,
			Explode: true,
		}

		if err := q.EncodeParam(cfg, func(e uri.Encoder) error {
			if val, ok := params.Version.Get(); ok {
				if unwrapped := string(val); true {
					return e.EncodeValue(conv.StringToString(unwrapped))
				}
				return nil
			}
			return nil
		}); err != nil {
			return res, errors.Wrap(err, "encode query")
		}
	}
	u.RawQuery = q.Values().Encode()

	stage = "EncodeRequest"
	r, err := ht.NewRequest(ctx, "GET", u)
	if err != nil {
		return res, errors.Wrap(err, "create request")
	}

	{
		type bitset = [1]uint8
		var satisfied bitset
		{
			stage = "Security:BffCookie"
			switch err := c.securityBffCookie(ctx, GenerateContentDownloadLinkOperation, r); {
			case err == nil: // if NO error
				satisfied[0] |= 1 << 0
			case errors.Is(err, ogenerrors.ErrSkipClientSecurity):
				// Skip this security.
			default:
				return res, errors.Wrap(err, "security \"BffCookie\"")
			}
		}

		if ok := func() bool {
		nextRequirement:
			for _, requirement := range []bitset{
				{0b00000001},
			} {
				for i, mask := range requirement {
					if satisfied[i]&mask != mask {
						continue nextRequirement
					}
				}
				return true
			}
			return false
		}(); !ok {
			return res, ogenerrors.ErrSecurityRequirementIsNotSatisfied
		}
	}

	if err := c.onRequest(ctx, r); err != nil {
		return res, errors.Wrap(err, "client edit request")
	}

	if err := reqCfg.onRequest(r); err != nil {
		return res, errors.Wrap(err, "edit request")
	}

	stage = "SendRequest"
	resp, err := reqCfg.Client.Do(r)
	if err != nil {
		return res, errors.Wrap(err, "do request")
	}
	body := resp.Body
	defer body.Close()

	if err := c.onResponse(ctx, resp); err != nil {
		return res, errors.Wrap(err, "client edit response")
	}

	if err := reqCfg.onResponse(resp); err != nil {
		return res, errors.Wrap(err, "edit response")
	}

	stage = "DecodeResponse"
	result, err := decodeGenerateContentDownloadLinkResponse(resp, reqCfg.DebugResponse)
	if err != nil {
		return res, errors.Wrap(err, "decode response")
	}

	return result, nil
}

// ListStudentCourses invokes listStudentCourses operation.
//
// Returns courses summary the authenticated student is enrolled in.
//
// GET /micro-lms/courses/student
func (c *Client) ListStudentCourses(ctx context.Context, params ListStudentCoursesParams, options ...RequestOption) (ListStudentCoursesRes, error) {
	return callClientDebugResponse(c, func(debugResponse *DebugResponse) (ListStudentCoursesRes, error) {
		return c.sendListStudentCourses(ctx, params, appendDebugResponseRequestOption(options, debugResponse)...)
	})

}

func (c *Client) sendListStudentCourses(ctx context.Context, params ListStudentCoursesParams, requestOptions ...RequestOption) (res ListStudentCoursesRes, err error) {
	otelAttrs := []attribute.KeyValue{
		otelogen.OperationID("listStudentCourses"),
		semconv.HTTPRequestMethodKey.String("GET"),
		semconv.URLTemplateKey.String("/micro-lms/courses/student"),
	}
	otelAttrs = append(otelAttrs, c.cfg.Attributes...)

	// Run stopwatch.
	startTime := time.Now()
	defer func() {
		// Use floating point division here for higher precision (instead of Millisecond method).
		elapsedDuration := time.Since(startTime)
		c.duration.Record(ctx, float64(elapsedDuration)/float64(time.Millisecond), metric.WithAttributes(otelAttrs...))
	}()

	// Increment request counter.
	c.requests.Add(ctx, 1, metric.WithAttributes(otelAttrs...))

	// Start a span for this request.
	ctx, span := c.cfg.Tracer.Start(ctx, ListStudentCoursesOperation,
		trace.WithAttributes(otelAttrs...),
		clientSpanKind,
	)
	// Track stage for error reporting.
	var stage string
	defer func() {
		if err != nil {
			span.RecordError(err)
			span.SetStatus(codes.Error, stage)
			c.errors.Add(ctx, 1, metric.WithAttributes(otelAttrs...))
		}
		span.End()
	}()

	var reqCfg requestConfig
	reqCfg.setDefaults(c.baseClient)
	for _, o := range requestOptions {
		o(&reqCfg)
	}

	stage = "BuildURL"
	u := c.serverURL
	if override := reqCfg.ServerURL; override != nil {
		u = override
	}
	u = uri.Clone(u)
	var pathParts [1]string
	pathParts[0] = "/micro-lms/courses/student"
	uri.AddPathParts(u, pathParts[:]...)

	stage = "EncodeQueryParams"
	q := uri.NewQueryEncoder()
	{
		// Encode "limit" parameter.
		cfg := uri.QueryParameterEncodingConfig{
			Name:    "limit",
			Style:   uri.QueryStyleForm,
			Explode: true,
		}

		if err := q.EncodeParam(cfg, func(e uri.Encoder) error {
			if val, ok := params.Limit.Get(); ok {
				return e.EncodeValue(conv.Int32ToString(val))
			}
			return nil
		}); err != nil {
			return res, errors.Wrap(err, "encode query")
		}
	}
	{
		// Encode "offset" parameter.
		cfg := uri.QueryParameterEncodingConfig{
			Name:    "offset",
			Style:   uri.QueryStyleForm,
			Explode: true,
		}

		if err := q.EncodeParam(cfg, func(e uri.Encoder) error {
			if val, ok := params.Offset.Get(); ok {
				return e.EncodeValue(conv.Int32ToString(val))
			}
			return nil
		}); err != nil {
			return res, errors.Wrap(err, "encode query")
		}
	}
	{
		// Encode "state" parameter.
		cfg := uri.QueryParameterEncodingConfig{
			Name:    "state",
			Style:   uri.QueryStyleForm,
			Explode: true,
		}

		if err := q.EncodeParam(cfg, func(e uri.Encoder) error {
			if params.State != nil {
				return e.EncodeArray(func(e uri.Encoder) error {
					for i, item := range params.State {
						if err := func() error {
							return e.EncodeValue(conv.StringToString(string(item)))
						}(); err != nil {
							return errors.Wrapf(err, "[%d]", i)
						}
					}
					return nil
				})
			}
			return nil
		}); err != nil {
			return res, errors.Wrap(err, "encode query")
		}
	}
	u.RawQuery = q.Values().Encode()

	stage = "EncodeRequest"
	r, err := ht.NewRequest(ctx, "GET", u)
	if err != nil {
		return res, errors.Wrap(err, "create request")
	}

	{
		type bitset = [1]uint8
		var satisfied bitset
		{
			stage = "Security:BffCookie"
			switch err := c.securityBffCookie(ctx, ListStudentCoursesOperation, r); {
			case err == nil: // if NO error
				satisfied[0] |= 1 << 0
			case errors.Is(err, ogenerrors.ErrSkipClientSecurity):
				// Skip this security.
			default:
				return res, errors.Wrap(err, "security \"BffCookie\"")
			}
		}

		if ok := func() bool {
		nextRequirement:
			for _, requirement := range []bitset{
				{0b00000001},
			} {
				for i, mask := range requirement {
					if satisfied[i]&mask != mask {
						continue nextRequirement
					}
				}
				return true
			}
			return false
		}(); !ok {
			return res, ogenerrors.ErrSecurityRequirementIsNotSatisfied
		}
	}

	if err := c.onRequest(ctx, r); err != nil {
		return res, errors.Wrap(err, "client edit request")
	}

	if err := reqCfg.onRequest(r); err != nil {
		return res, errors.Wrap(err, "edit request")
	}

	stage = "SendRequest"
	resp, err := reqCfg.Client.Do(r)
	if err != nil {
		return res, errors.Wrap(err, "do request")
	}
	body := resp.Body
	defer body.Close()

	if err := c.onResponse(ctx, resp); err != nil {
		return res, errors.Wrap(err, "client edit response")
	}

	if err := reqCfg.onResponse(resp); err != nil {
		return res, errors.Wrap(err, "edit response")
	}

	stage = "DecodeResponse"
	result, err := decodeListStudentCoursesResponse(resp, reqCfg.DebugResponse)
	if err != nil {
		return res, errors.Wrap(err, "decode response")
	}

	return result, nil
}

// LongreadMaterialsById invokes longreadMaterialsById operation.
//
// Returns longread materials by longreadId. Materials are blocks like markdown, files and exercises.
// Blocks are declared for each longread.
//
// GET /micro-lms/longreads/{longreadId}/materials
func (c *Client) LongreadMaterialsById(ctx context.Context, params LongreadMaterialsByIdParams, options ...RequestOption) (LongreadMaterialsByIdRes, error) {
	return callClientDebugResponse(c, func(debugResponse *DebugResponse) (LongreadMaterialsByIdRes, error) {
		return c.sendLongreadMaterialsById(ctx, params, appendDebugResponseRequestOption(options, debugResponse)...)
	})

}

func (c *Client) sendLongreadMaterialsById(ctx context.Context, params LongreadMaterialsByIdParams, requestOptions ...RequestOption) (res LongreadMaterialsByIdRes, err error) {
	otelAttrs := []attribute.KeyValue{
		otelogen.OperationID("longreadMaterialsById"),
		semconv.HTTPRequestMethodKey.String("GET"),
		semconv.URLTemplateKey.String("/micro-lms/longreads/{longreadId}/materials"),
	}
	otelAttrs = append(otelAttrs, c.cfg.Attributes...)

	// Run stopwatch.
	startTime := time.Now()
	defer func() {
		// Use floating point division here for higher precision (instead of Millisecond method).
		elapsedDuration := time.Since(startTime)
		c.duration.Record(ctx, float64(elapsedDuration)/float64(time.Millisecond), metric.WithAttributes(otelAttrs...))
	}()

	// Increment request counter.
	c.requests.Add(ctx, 1, metric.WithAttributes(otelAttrs...))

	// Start a span for this request.
	ctx, span := c.cfg.Tracer.Start(ctx, LongreadMaterialsByIdOperation,
		trace.WithAttributes(otelAttrs...),
		clientSpanKind,
	)
	// Track stage for error reporting.
	var stage string
	defer func() {
		if err != nil {
			span.RecordError(err)
			span.SetStatus(codes.Error, stage)
			c.errors.Add(ctx, 1, metric.WithAttributes(otelAttrs...))
		}
		span.End()
	}()

	var reqCfg requestConfig
	reqCfg.setDefaults(c.baseClient)
	for _, o := range requestOptions {
		o(&reqCfg)
	}

	stage = "BuildURL"
	u := c.serverURL
	if override := reqCfg.ServerURL; override != nil {
		u = override
	}
	u = uri.Clone(u)
	var pathParts [3]string
	pathParts[0] = "/micro-lms/longreads/"
	{
		// Encode "longreadId" parameter.
		e := uri.NewPathEncoder(uri.PathEncoderConfig{
			Param:   "longreadId",
			Style:   uri.PathStyleSimple,
			Explode: false,
		})
		if err := func() error {
			if unwrapped := int(params.LongreadId); true {
				return e.EncodeValue(conv.IntToString(unwrapped))
			}
			return nil
		}(); err != nil {
			return res, errors.Wrap(err, "encode path")
		}
		encoded, err := e.Result()
		if err != nil {
			return res, errors.Wrap(err, "encode path")
		}
		pathParts[1] = encoded
	}
	pathParts[2] = "/materials"
	uri.AddPathParts(u, pathParts[:]...)

	stage = "EncodeQueryParams"
	q := uri.NewQueryEncoder()
	{
		// Encode "limit" parameter.
		cfg := uri.QueryParameterEncodingConfig{
			Name:    "limit",
			Style:   uri.QueryStyleForm,
			Explode: true,
		}

		if err := q.EncodeParam(cfg, func(e uri.Encoder) error {
			if val, ok := params.Limit.Get(); ok {
				return e.EncodeValue(conv.Int32ToString(val))
			}
			return nil
		}); err != nil {
			return res, errors.Wrap(err, "encode query")
		}
	}
	{
		// Encode "offset" parameter.
		cfg := uri.QueryParameterEncodingConfig{
			Name:    "offset",
			Style:   uri.QueryStyleForm,
			Explode: true,
		}

		if err := q.EncodeParam(cfg, func(e uri.Encoder) error {
			if val, ok := params.Offset.Get(); ok {
				return e.EncodeValue(conv.Int32ToString(val))
			}
			return nil
		}); err != nil {
			return res, errors.Wrap(err, "encode query")
		}
	}
	u.RawQuery = q.Values().Encode()

	stage = "EncodeRequest"
	r, err := ht.NewRequest(ctx, "GET", u)
	if err != nil {
		return res, errors.Wrap(err, "create request")
	}

	{
		type bitset = [1]uint8
		var satisfied bitset
		{
			stage = "Security:BffCookie"
			switch err := c.securityBffCookie(ctx, LongreadMaterialsByIdOperation, r); {
			case err == nil: // if NO error
				satisfied[0] |= 1 << 0
			case errors.Is(err, ogenerrors.ErrSkipClientSecurity):
				// Skip this security.
			default:
				return res, errors.Wrap(err, "security \"BffCookie\"")
			}
		}

		if ok := func() bool {
		nextRequirement:
			for _, requirement := range []bitset{
				{0b00000001},
			} {
				for i, mask := range requirement {
					if satisfied[i]&mask != mask {
						continue nextRequirement
					}
				}
				return true
			}
			return false
		}(); !ok {
			return res, ogenerrors.ErrSecurityRequirementIsNotSatisfied
		}
	}

	if err := c.onRequest(ctx, r); err != nil {
		return res, errors.Wrap(err, "client edit request")
	}

	if err := reqCfg.onRequest(r); err != nil {
		return res, errors.Wrap(err, "edit request")
	}

	stage = "SendRequest"
	resp, err := reqCfg.Client.Do(r)
	if err != nil {
		return res, errors.Wrap(err, "do request")
	}
	body := resp.Body
	defer body.Close()

	if err := c.onResponse(ctx, resp); err != nil {
		return res, errors.Wrap(err, "client edit response")
	}

	if err := reqCfg.onResponse(resp); err != nil {
		return res, errors.Wrap(err, "edit response")
	}

	stage = "DecodeResponse"
	result, err := decodeLongreadMaterialsByIdResponse(resp, reqCfg.DebugResponse)
	if err != nil {
		return res, errors.Wrap(err, "decode response")
	}

	return result, nil
}

// LongreadSummaryById invokes longreadSummaryById operation.
//
// Returns summary information about a longread item by longreadId.
//
// GET /micro-lms/longreads/{longreadId}
func (c *Client) LongreadSummaryById(ctx context.Context, params LongreadSummaryByIdParams, options ...RequestOption) (LongreadSummaryByIdRes, error) {
	return callClientDebugResponse(c, func(debugResponse *DebugResponse) (LongreadSummaryByIdRes, error) {
		return c.sendLongreadSummaryById(ctx, params, appendDebugResponseRequestOption(options, debugResponse)...)
	})

}

func (c *Client) sendLongreadSummaryById(ctx context.Context, params LongreadSummaryByIdParams, requestOptions ...RequestOption) (res LongreadSummaryByIdRes, err error) {
	otelAttrs := []attribute.KeyValue{
		otelogen.OperationID("longreadSummaryById"),
		semconv.HTTPRequestMethodKey.String("GET"),
		semconv.URLTemplateKey.String("/micro-lms/longreads/{longreadId}"),
	}
	otelAttrs = append(otelAttrs, c.cfg.Attributes...)

	// Run stopwatch.
	startTime := time.Now()
	defer func() {
		// Use floating point division here for higher precision (instead of Millisecond method).
		elapsedDuration := time.Since(startTime)
		c.duration.Record(ctx, float64(elapsedDuration)/float64(time.Millisecond), metric.WithAttributes(otelAttrs...))
	}()

	// Increment request counter.
	c.requests.Add(ctx, 1, metric.WithAttributes(otelAttrs...))

	// Start a span for this request.
	ctx, span := c.cfg.Tracer.Start(ctx, LongreadSummaryByIdOperation,
		trace.WithAttributes(otelAttrs...),
		clientSpanKind,
	)
	// Track stage for error reporting.
	var stage string
	defer func() {
		if err != nil {
			span.RecordError(err)
			span.SetStatus(codes.Error, stage)
			c.errors.Add(ctx, 1, metric.WithAttributes(otelAttrs...))
		}
		span.End()
	}()

	var reqCfg requestConfig
	reqCfg.setDefaults(c.baseClient)
	for _, o := range requestOptions {
		o(&reqCfg)
	}

	stage = "BuildURL"
	u := c.serverURL
	if override := reqCfg.ServerURL; override != nil {
		u = override
	}
	u = uri.Clone(u)
	var pathParts [2]string
	pathParts[0] = "/micro-lms/longreads/"
	{
		// Encode "longreadId" parameter.
		e := uri.NewPathEncoder(uri.PathEncoderConfig{
			Param:   "longreadId",
			Style:   uri.PathStyleSimple,
			Explode: false,
		})
		if err := func() error {
			if unwrapped := int(params.LongreadId); true {
				return e.EncodeValue(conv.IntToString(unwrapped))
			}
			return nil
		}(); err != nil {
			return res, errors.Wrap(err, "encode path")
		}
		encoded, err := e.Result()
		if err != nil {
			return res, errors.Wrap(err, "encode path")
		}
		pathParts[1] = encoded
	}
	uri.AddPathParts(u, pathParts[:]...)

	stage = "EncodeRequest"
	r, err := ht.NewRequest(ctx, "GET", u)
	if err != nil {
		return res, errors.Wrap(err, "create request")
	}

	{
		type bitset = [1]uint8
		var satisfied bitset
		{
			stage = "Security:BffCookie"
			switch err := c.securityBffCookie(ctx, LongreadSummaryByIdOperation, r); {
			case err == nil: // if NO error
				satisfied[0] |= 1 << 0
			case errors.Is(err, ogenerrors.ErrSkipClientSecurity):
				// Skip this security.
			default:
				return res, errors.Wrap(err, "security \"BffCookie\"")
			}
		}

		if ok := func() bool {
		nextRequirement:
			for _, requirement := range []bitset{
				{0b00000001},
			} {
				for i, mask := range requirement {
					if satisfied[i]&mask != mask {
						continue nextRequirement
					}
				}
				return true
			}
			return false
		}(); !ok {
			return res, ogenerrors.ErrSecurityRequirementIsNotSatisfied
		}
	}

	if err := c.onRequest(ctx, r); err != nil {
		return res, errors.Wrap(err, "client edit request")
	}

	if err := reqCfg.onRequest(r); err != nil {
		return res, errors.Wrap(err, "edit request")
	}

	stage = "SendRequest"
	resp, err := reqCfg.Client.Do(r)
	if err != nil {
		return res, errors.Wrap(err, "do request")
	}
	body := resp.Body
	defer body.Close()

	if err := c.onResponse(ctx, resp); err != nil {
		return res, errors.Wrap(err, "client edit response")
	}

	if err := reqCfg.onResponse(resp); err != nil {
		return res, errors.Wrap(err, "edit response")
	}

	stage = "DecodeResponse"
	result, err := decodeLongreadSummaryByIdResponse(resp, reqCfg.DebugResponse)
	if err != nil {
		return res, errors.Wrap(err, "decode response")
	}

	return result, nil
}

// TaskById invokes taskById operation.
//
// Returns task by taskId.
//
// GET /micro-lms/tasks/{taskId}
func (c *Client) TaskById(ctx context.Context, params TaskByIdParams, options ...RequestOption) (TaskByIdRes, error) {
	return callClientDebugResponse(c, func(debugResponse *DebugResponse) (TaskByIdRes, error) {
		return c.sendTaskById(ctx, params, appendDebugResponseRequestOption(options, debugResponse)...)
	})

}

func (c *Client) sendTaskById(ctx context.Context, params TaskByIdParams, requestOptions ...RequestOption) (res TaskByIdRes, err error) {
	otelAttrs := []attribute.KeyValue{
		otelogen.OperationID("taskById"),
		semconv.HTTPRequestMethodKey.String("GET"),
		semconv.URLTemplateKey.String("/micro-lms/tasks/{taskId}"),
	}
	otelAttrs = append(otelAttrs, c.cfg.Attributes...)

	// Run stopwatch.
	startTime := time.Now()
	defer func() {
		// Use floating point division here for higher precision (instead of Millisecond method).
		elapsedDuration := time.Since(startTime)
		c.duration.Record(ctx, float64(elapsedDuration)/float64(time.Millisecond), metric.WithAttributes(otelAttrs...))
	}()

	// Increment request counter.
	c.requests.Add(ctx, 1, metric.WithAttributes(otelAttrs...))

	// Start a span for this request.
	ctx, span := c.cfg.Tracer.Start(ctx, TaskByIdOperation,
		trace.WithAttributes(otelAttrs...),
		clientSpanKind,
	)
	// Track stage for error reporting.
	var stage string
	defer func() {
		if err != nil {
			span.RecordError(err)
			span.SetStatus(codes.Error, stage)
			c.errors.Add(ctx, 1, metric.WithAttributes(otelAttrs...))
		}
		span.End()
	}()

	var reqCfg requestConfig
	reqCfg.setDefaults(c.baseClient)
	for _, o := range requestOptions {
		o(&reqCfg)
	}

	stage = "BuildURL"
	u := c.serverURL
	if override := reqCfg.ServerURL; override != nil {
		u = override
	}
	u = uri.Clone(u)
	var pathParts [2]string
	pathParts[0] = "/micro-lms/tasks/"
	{
		// Encode "taskId" parameter.
		e := uri.NewPathEncoder(uri.PathEncoderConfig{
			Param:   "taskId",
			Style:   uri.PathStyleSimple,
			Explode: false,
		})
		if err := func() error {
			if unwrapped := int(params.TaskId); true {
				return e.EncodeValue(conv.IntToString(unwrapped))
			}
			return nil
		}(); err != nil {
			return res, errors.Wrap(err, "encode path")
		}
		encoded, err := e.Result()
		if err != nil {
			return res, errors.Wrap(err, "encode path")
		}
		pathParts[1] = encoded
	}
	uri.AddPathParts(u, pathParts[:]...)

	stage = "EncodeRequest"
	r, err := ht.NewRequest(ctx, "GET", u)
	if err != nil {
		return res, errors.Wrap(err, "create request")
	}

	{
		type bitset = [1]uint8
		var satisfied bitset
		{
			stage = "Security:BffCookie"
			switch err := c.securityBffCookie(ctx, TaskByIdOperation, r); {
			case err == nil: // if NO error
				satisfied[0] |= 1 << 0
			case errors.Is(err, ogenerrors.ErrSkipClientSecurity):
				// Skip this security.
			default:
				return res, errors.Wrap(err, "security \"BffCookie\"")
			}
		}

		if ok := func() bool {
		nextRequirement:
			for _, requirement := range []bitset{
				{0b00000001},
			} {
				for i, mask := range requirement {
					if satisfied[i]&mask != mask {
						continue nextRequirement
					}
				}
				return true
			}
			return false
		}(); !ok {
			return res, ogenerrors.ErrSecurityRequirementIsNotSatisfied
		}
	}

	if err := c.onRequest(ctx, r); err != nil {
		return res, errors.Wrap(err, "client edit request")
	}

	if err := reqCfg.onRequest(r); err != nil {
		return res, errors.Wrap(err, "edit request")
	}

	stage = "SendRequest"
	resp, err := reqCfg.Client.Do(r)
	if err != nil {
		return res, errors.Wrap(err, "do request")
	}
	body := resp.Body
	defer body.Close()

	if err := c.onResponse(ctx, resp); err != nil {
		return res, errors.Wrap(err, "client edit response")
	}

	if err := reqCfg.onResponse(resp); err != nil {
		return res, errors.Wrap(err, "edit response")
	}

	stage = "DecodeResponse"
	result, err := decodeTaskByIdResponse(resp, reqCfg.DebugResponse)
	if err != nil {
		return res, errors.Wrap(err, "decode response")
	}

	return result, nil
}
