// Code generated by ogen, DO NOT EDIT.

package lmsapi

// CourseOverviewByIdParams is parameters of courseOverviewById operation.
type CourseOverviewByIdParams struct {
	// Numeric identifier of the course specified in URL path.
	CourseId CourseId
}

// CourseSummaryByIdParams is parameters of courseSummaryById operation.
type CourseSummaryByIdParams struct {
	// Numeric identifier of the course specified in URL path.
	CourseId CourseId
}

// CourseThemeSummaryByIdParams is parameters of courseThemeSummaryById operation.
type CourseThemeSummaryByIdParams struct {
	// Numeric identifier of the course theme specified in URL path.
	ThemeId CourseThemeId
}

// GenerateContentDownloadLinkParams is parameters of generateContentDownloadLink operation.
type GenerateContentDownloadLinkParams struct {
	// File object path in storage specified in URL query.
	Filename FileNameObjectPath
	// Material content revision identifier specified in URL query.
	Version OptNilLongreadMaterialVersion `json:",omitempty,omitzero"`
}

// ListStudentCoursesParams is parameters of listStudentCourses operation.
type ListStudentCoursesParams struct {
	// Maximum number of items to return.
	Limit OptInt32 `json:",omitempty,omitzero"`
	// Number of items to skip before collecting result items.
	Offset OptInt32 `json:",omitempty,omitzero"`
	// Include only courses whose state matches any of the specified values.
	State []PublicationState `json:",omitempty"`
}

// LongreadMaterialsByIdParams is parameters of longreadMaterialsById operation.
type LongreadMaterialsByIdParams struct {
	// Numeric identifier of the longread item specified in URL path.
	LongreadId LongreadId
	// Maximum number of items to return.
	Limit OptInt32 `json:",omitempty,omitzero"`
	// Number of items to skip before collecting result items.
	Offset OptInt32 `json:",omitempty,omitzero"`
}

// LongreadSummaryByIdParams is parameters of longreadSummaryById operation.
type LongreadSummaryByIdParams struct {
	// Numeric identifier of the longread item specified in URL path.
	LongreadId LongreadId
}

// TaskByIdParams is parameters of taskById operation.
type TaskByIdParams struct {
	// Numeric identifier of the task item specified in URL path.
	TaskId TaskId
}
