// Code generated by ogen, DO NOT EDIT.

package lmsapi

import (
	"context"
	"net/http"

	"github.com/go-faster/errors"
)

// SecuritySource is provider of security values (tokens, passwords, etc.).
type SecuritySource interface {
	// BffCookie provides BffCookie security value.
	// Session cookie used to authenticate the user when calling the LMS API.
	BffCookie(ctx context.Context, operationName OperationName) (BffCookie, error)
}

// operationRolesBffCookie is a private map storing roles per operation.
var operationRolesBffCookie = map[string][]string{
	CourseOverviewByIdOperation:          []string{},
	CourseSummaryByIdOperation:           []string{},
	CourseThemeSummaryByIdOperation:      []string{},
	CurrentStudentOperation:              []string{},
	GenerateContentDownloadLinkOperation: []string{},
	ListStudentCoursesOperation:          []string{},
	LongreadMaterialsByIdOperation:       []string{},
	LongreadSummaryByIdOperation:         []string{},
	TaskByIdOperation:                    []string{},
}

// GetRolesForBffCookie returns the required roles for the given operation.
//
// This is useful for authorization scenarios where you need to know which roles
// are required for an operation.
//
// Example:
//
//	requiredRoles := GetRolesForBffCookie(AddPetOperation)
//
// Returns nil if the operation has no role requirements or if the operation is unknown.
func GetRolesForBffCookie(operation string) []string {
	roles, ok := operationRolesBffCookie[operation]
	if !ok {
		return nil
	}
	// Return a copy to prevent external modification
	result := make([]string, len(roles))
	copy(result, roles)
	return result
}

func (s *Client) securityBffCookie(ctx context.Context, operationName OperationName, req *http.Request) error {
	t, err := s.sec.BffCookie(ctx, operationName)
	if err != nil {
		return errors.Wrap(err, "security source \"BffCookie\"")
	}
	req.AddCookie(&http.Cookie{
		Name:  "bff.cookie",
		Value: t.APIKey,
	})
	return nil
}
