// Code generated by ogen, DO NOT EDIT.

package lmsapi

// OperationName is the ogen operation name
type OperationName = string

const (
	CourseOverviewByIdOperation          OperationName = "CourseOverviewById"
	CourseSummaryByIdOperation           OperationName = "CourseSummaryById"
	CourseThemeSummaryByIdOperation      OperationName = "CourseThemeSummaryById"
	CurrentStudentOperation              OperationName = "CurrentStudent"
	GenerateContentDownloadLinkOperation OperationName = "GenerateContentDownloadLink"
	ListStudentCoursesOperation          OperationName = "ListStudentCourses"
	LongreadMaterialsByIdOperation       OperationName = "LongreadMaterialsById"
	LongreadSummaryByIdOperation         OperationName = "LongreadSummaryById"
	TaskByIdOperation                    OperationName = "TaskById"
)
