// Code generated by ogen, DO NOT EDIT.
package lmsapi

type CourseOverviewByIdRes interface {
	courseOverviewByIdRes()
}

type CourseSummaryByIdRes interface {
	courseSummaryByIdRes()
}

type CourseThemeSummaryByIdRes interface {
	courseThemeSummaryByIdRes()
}

type CurrentStudentRes interface {
	currentStudentRes()
}

type GenerateContentDownloadLinkRes interface {
	generateContentDownloadLinkRes()
}

type ListStudentCoursesRes interface {
	listStudentCoursesRes()
}

type LongreadMaterialsByIdRes interface {
	longreadMaterialsByIdRes()
}

type LongreadSummaryByIdRes interface {
	longreadSummaryByIdRes()
}

type TaskByIdRes interface {
	taskByIdRes()
}
