// Code generated by gen-sdk-golang, DO NOT EDIT.

package lmsapi

import (
	"errors"
	"fmt"

	"github.com/ogen-go/ogen/ogenerrors"
	"github.com/ogen-go/ogen/validate"
)

// ResponseSpecError reports that a server response did not match the spec
// contract during decoding or validation.
type ResponseSpecError struct {
	ContentType string
	Body        []byte
	Fields      []validate.FieldError
	Err         error
}

func (e *ResponseSpecError) Unwrap() error {
	return e.Err
}

func (e *ResponseSpecError) Error() string {
	if len(e.Fields) > 0 {
		return (&validate.Error{Fields: e.Fields}).Error()
	}
	if e.ContentType != "" {
		return fmt.Sprintf("decode %s: %v", e.ContentType, e.Err)
	}
	if e.Err != nil {
		return e.Err.Error()
	}
	return "response does not match schema"
}

// AsResponseSpecError extracts response contract errors returned by an
// operation call.
func AsResponseSpecError(err error) (*ResponseSpecError, bool) {
	var decodeBodyErr *ogenerrors.DecodeBodyError
	var validationErr *validate.Error

	var specErr = new(ResponseSpecError)

	// TODO: change to errors.AsType after migration to Go 1.26.
	if errors.As(err, &decodeBodyErr) {
		specErr.ContentType = decodeBodyErr.ContentType
		specErr.Body = decodeBodyErr.Body
		specErr.Err = decodeBodyErr.Err
	}
	if errors.As(err, &validationErr) {
		specErr.Fields = validationErr.Fields
		if specErr.Err == nil {
			specErr.Err = validationErr
		}
	}

	if specErr.Err == nil {
		return nil, false
	}

	return specErr, true
}
