// GENERATED CODE - DO NOT MODIFY BY HAND

// This file is generated by gen-sdk-dart.

import 'dart:async';
import 'package:chopper/chopper.dart';
import 'package:http/http.dart' as http;

import 'debug_response.dart';
import 'generated/lms_api.swagger.dart';

const String defaultBaseUrl = "https://my.centraluniversity.ru/api";
const String defaultUserAgent = "Open-CU-Services/Dart";
const String sdkVersion = "0.1.0";
const String specVersion = "0.1.0";
const String bffCookieName = "bff.cookie";
const bool isDartVmRuntime =
    bool.fromEnvironment("dart.library.io") &&
    !bool.fromEnvironment("dart.library.ui");

class BffCookieIsEmptyError implements Exception {
  const BffCookieIsEmptyError();

  @override
  String toString() => "BffCookieIsEmptyError: bffCookie is empty";
}

class LmsApiUnhandledError extends Error {
  LmsApiUnhandledError({required this.statusCode, this.body, this.cause});

  final int statusCode;
  final Object? body;
  final Object? cause;

  @override
  String toString() =>
      "LmsApiUnhandledError(statusCode: $statusCode, body: $body, cause: $cause)";
}

LmsApi createLmsApiClient({
  required String bffCookie,
  String baseUrl = defaultBaseUrl,
  http.Client? httpClient,
  Authenticator? authenticator,
  ErrorConverter? errorConverter,
  Converter? converter,
  List<Interceptor>? interceptors,
  DebugResponseOptions? debugResponseOptions,
}) {
  if (bffCookie.isEmpty) {
    throw const BffCookieIsEmptyError();
  }

  final resolvedConverter = converter ?? $JsonSerializableConverter();
  final resolvedDebugResponses = DebugResponses(
    client: defaultUserAgent,
    sdkVersion: sdkVersion,
    specVersion: specVersion,
    options: debugResponseOptions ?? DebugResponseOptions.defaults,
  );
  final resolvedInterceptors = <Interceptor>[
    _BffCookieInterceptor(bffCookie),
    if (isDartVmRuntime) _UserAgentInterceptor(defaultUserAgent),
    ...?interceptors,
  ];

  return LmsApi.create(
    httpClient: httpClient,
    authenticator: authenticator,
    errorConverter: DebugResponseErrorConverter(
      delegate: errorConverter ?? _LmsApiErrorConverter(resolvedConverter),
      debugResponses: resolvedDebugResponses,
    ),
    converter: DebugResponseConverter(
      delegate: resolvedConverter,
      debugResponses: resolvedDebugResponses,
    ),
    baseUrl: Uri.parse(baseUrl),
    interceptors: resolvedInterceptors,
  );
}

class _LmsApiErrorConverter implements ErrorConverter {
  const _LmsApiErrorConverter(this.converter);

  final Converter converter;

  @override
  FutureOr<Response> convertError<BodyType, InnerType>(
    Response response,
  ) async {
    final decoded = await _decodeJsonError(response);
    final body = decoded.body;
    if (body is! Map<String, dynamic>) {
      return decoded.copyWith(
        bodyError: LmsApiUnhandledError(
          statusCode: response.statusCode,
          body: body,
        ),
      );
    }

    try {
      final error = switch (response.statusCode) {
        400 => BaseBadRequestError.fromJson(body),
        401 => BaseUnauthorizedError.fromJson(body),
        404 => BaseNotFoundError.fromJson(body),
        _ => BaseProblemError.fromJson(body),
      };

      return decoded.copyWith(bodyError: error);
    } catch (cause) {
      return decoded.copyWith(
        bodyError: LmsApiUnhandledError(
          statusCode: response.statusCode,
          body: body,
          cause: cause,
        ),
      );
    }
  }

  Future<Response> _decodeJsonError(Response response) async {
    final delegate = converter is ErrorConverter
        ? converter as ErrorConverter
        : const JsonConverter();
    return await delegate
        .convertError<Map<String, dynamic>, Map<String, dynamic>>(response);
  }
}

class _BffCookieInterceptor implements Interceptor {
  const _BffCookieInterceptor(this.bffCookie);

  final String bffCookie;

  @override
  FutureOr<Response<BodyType>> intercept<BodyType>(Chain<BodyType> chain) {
    final request = applyHeader(
      chain.request,
      "Cookie",
      "$bffCookieName=$bffCookie",
    );

    return chain.proceed(request);
  }
}

class _UserAgentInterceptor implements Interceptor {
  const _UserAgentInterceptor(this.userAgent);

  final String userAgent;

  @override
  FutureOr<Response<BodyType>> intercept<BodyType>(Chain<BodyType> chain) {
    if (userAgent.isEmpty) {
      return chain.proceed(chain.request);
    }

    final request = applyHeader(
      chain.request,
      "User-Agent",
      userAgent,
      override: false,
    );

    return chain.proceed(request);
  }
}
